import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'C# Fundamentals',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '01-csharp-fundamentals'}],
    },
    {
      type: 'category',
      label: 'C# Advanced',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '02-csharp-advanced'}],
    },
    {
      type: 'category',
      label: 'LINQ & Collections',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '03-linq-collections'}],
    },
    {
      type: 'category',
      label: 'Async & Parallel',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '04-async-parallel'}],
    },
    {
      type: 'category',
      label: 'OOP Principles',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '05-oop-principles'}],
    },
    {
      type: 'category',
      label: 'SOLID Principles',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '06-solid-principles'}],
    },
    {
      type: 'category',
      label: 'Design Patterns',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '07-design-patterns'}],
    },
    {
      type: 'category',
      label: '.NET Runtime',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '08-dotnet-runtime'}],
    },
    {
      type: 'category',
      label: 'ASP.NET Core & Web API',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '09-aspnetcore-webapi'}],
    },
    {
      type: 'category',
      label: 'Entity Framework & Databases',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '10-ef-databases'}],
    },
    {
      type: 'category',
      label: 'Testing',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '11-testing'}],
    },
    {
      type: 'category',
      label: 'Architecture & DDD',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '12-architecture-ddd'}],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '13-security'}],
    },
    {
      type: 'category',
      label: 'Performance',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '14-performance'}],
    },
    {
      type: 'category',
      label: 'DevOps & CI/CD',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '15-devops-cicd'}],
    },
    {
      type: 'category',
      label: 'Interview Questions',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '16-interview-questions'}],
    },
  ],
};

export default sidebars;
